config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :people

  root 'people#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    validates_length_of :city, in: 2..32, allow_nil: false
    validates_length_of :street, in: 2..48, allow_nil: false
    validates :psc, length: { is: 5 }, allow_blank: false
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :locations
    validates_length_of :name, in: 2..32, allow_nil: false
    validates_length_of :surname, in: 2..32, allow_nil: false
    validates_length_of :phoneNumber, in: 9..32, allow_nil: false
    validates_format_of :birthNumber, with: /\A([0-9]{6}+)\/+[0-9]{3,4}\z/i
    validates :birthNumber, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @people = Person.all
    @locations = Kaminari.paginate_array(@locations).page(params[:page]).per(10)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Adresa byla vytvořena.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Adresa byla upravena.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Adresa byla smazána.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:street, :city, :psc, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session
  
  # GET /people
  # GET /people.json
  def index
    @people = Person.order(:surname)
    @people = Kaminari.paginate_array(@people).page(params[:page]).per(10)
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @locations = Location.all
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    
    
    @person.dateOfBirth = getDateFromBirthDate(person_params[:birthNumber])
    @person.sex = getSexFromBirthDate(person_params[:birthNumber])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Osoba byla vytvořena.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      new_person_params = person_params 
      new_person_params['dateOfBirth'] = getDateFromBirthDate(person_params[:birthNumber])
      new_person_params['sex'] = getSexFromBirthDate(person_params[:birthNumber])
      if @person.update(new_person_params)
        format.html { redirect_to @person, notice: 'Osoba byla upravena.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Osoba byla úspěšně smazána.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :surname, :birthNumber, :phoneNumber, :sex, :dateOfBirth)
    end

    private

    def getDateFromBirthDate(birthDate)
      birthMonth = birthDate[2,2].to_i > 50 ? birthDate[2,2].to_i-50 : birthDate[2,2].to_i
      birthMonth = birthMonth.to_s.length == 2 ? birthMonth : "0"+birthMonth.to_s
      if birthDate[0,2].to_i < 54 && birthDate.length != 10
        birthYear = "20"+birthDate[0,2]
      else
        birthYear = "19"+birthDate[0,2]
      end
      return "#{birthDate[4,2]}/#{birthMonth}/#{birthYear}"
    end

    def getSexFromBirthDate(birthDate)
      return birthDate[2,2].to_i > 50 ? 'Žena' : 'Muž'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_footer.html.erb
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"><i class="fas fa-address-book"></i> ADDRESS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/people">Seznam kontaktů</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/locations">Seznam Adres</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/people/new">Přidat kontakt</a>
      </li>
    </ul>
  </div>
</nav>
<% if notice  %>
  <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Address</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/fb1e4c80a0.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render "layouts/header" %>
  <%=yield %>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :psc %>
    <%= form.number_field :psc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<% if @location.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>
 
    <ul>
    <% @location.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1 class="display-2 text-center">Upravit adresu kontaktu</h1>   

<div class="container">
    <%= form_for @location do |form| %>
        <div class="form-group">
            <%= form.label :street, "Ulice:" %>
            <%= form.text_field :street, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :city, "Město:" %>
            <%= form.text_field :city, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :psc, "PSČ:" %>
            <%= form.text_field :psc, class: "form-control" %>
        </div>
        <div class="form-group">
            <input class="hidden" type="text" name="location[person_id]" value="<%= @location.person_id  %>" id="location_person_id">
        </div>
        <div class="form-group text-center">
            <%= form.submit 'Odeslat', :class => 'btn btn-outline-primary btn-md' %>
            <a href="/locations/<%= @location.id %>" class="btn btn-outline-secondary btn-md">Zpátky...</a>
        </div>
    <% end %>
</div>

app/views/locations/index.html.erb
<div class="row m-0 justify-content-center">
  <div class="col-xl-10 col-lg-12">
    <div class="text-center">
    <h1 class="display-3">Adresář</h1>
    </div>

    <table class="table">
    <thead class="thead-light">
        <tr>
          <th>Město</th>
          <th>Ulice</th>
          <th>PSČ</th>
          <th>Uživatel</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @locations.each do |location| %>
          <% person = @people.find(location.person_id) %>
          <tr> 
            <td class="align-middle"><%= location.city %></td>
            <td class="align-middle"><%= location.street %></td>
            <td class="align-middle"><%= location.psc %></td>
            <td class="align-middle"><a href="/people/<%= location.person_id %>"><i class="fas fa-male"></i> <%= person.name %> <%= person.surname %></i></a></td>
            <td class="align-middle"><%= link_to 'Ukázat', location, :class => "btn btn-outline-primary" %></td>
            <td class="align-middle"><%= link_to 'Editovat', edit_location_path(location), :class => "btn btn-outline-secondary" %></td>
            <td class="align-middle"><%= link_to 'Smazat', location, :class => "btn btn-outline-danger", method: :delete, data: { confirm: 'Jste si jistý/á?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center"><%= paginate @locations %></div>
  </div>
</div>

app/views/locations/new.html.erb
<% if @location.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>
 
    <ul>
    <% @location.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1 class="display-2 text-center">Přidat adresu kontaktu</h1>   

<div class="container">
    <%= form_for @location do |form| %>
        <div class="form-group">
            <%= form.label :street, "Ulice:" %>
            <%= form.text_field :street, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :city, "Město:" %>
            <%= form.text_field :city, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :psc, "PSČ:" %>
            <%= form.text_field :psc, class: "form-control" %>
        </div>
        <div class="form-group">
            <input class="hidden" type="text" name="location[person_id]" value="<%= params[:person_id] %>" id="location_person_id">
        </div>
        <div class="form-group text-center">
            <%= form.submit 'Odeslat', :class => 'btn btn-outline-primary btn-md' %>
            <a href="/people/<%= params[:person_id] %>" class="btn btn-outline-secondary btn-md">Zpátky...</a>
        </div>
    <% end %>
</div>

app/views/locations/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Adresář</a></li>
    <li class="breadcrumb-item"><a href="/people/<%= @location.person_id %>">Osoba</a></li>
    <li class="breadcrumb-item active" aria-current="page">Adresa</li>
  </ol>
</nav>

<div class="container">
  <ul class="list-group pl-5 pr-5">
    <li class="list-group-item">
      <p>
        <i class="fas fa-road"></i>
        <strong>Street:</strong>
        <%= @location.street %>
      </p>
    </li>
    <li class="list-group-item">
      <p>
        <i class="fas fa-city"></i>
        <strong>City:</strong>
        <%= @location.city %>
      </p>
    </li>
    <li class="list-group-item">
      <p>
        <i class="fas fa-mail-bulk"></i>
        <strong>Psc:</strong>
        <%= @location.psc %>
      </p>
    </li>
  </ul>
  <div class="navigationButtons text-center">
      <%= link_to 'Edit', edit_location_path(@location) %> |
      <%= link_to 'Back', "/people/#{@location.person_id}" %>
  <div>
</div>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :birthNumber %>
    <%= form.text_field :birthNumber %>
  </div>

  <div class="field">
    <%= form.label :phoneNumber %>
    <%= form.text_field :phoneNumber %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :dateOfBirth %>
    <%= form.text_field :dateOfBirth %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<% if @person.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>
 
    <ul>
    <% @person.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1 class="display-2 text-center">Upravit kontakt v adresáři</h1>

    <div class="container">
        <%= form_for @person do |form| %>
            <div class="form-group">
                <%= form.label :name, "Jméno:" %>
                <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :surname, "Příjmení:" %>
                <%= form.text_field :surname, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :birthNumber, "Rodné číslo:" %>
                <%= form.text_field :birthNumber, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :phoneNumber, "Telefon:" %>
                <%= form.text_field :phoneNumber, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.text_field :sex, class: "hidden" %>
            </div>
            <div class="form-group">
                <%= form.text_field :dateOfBirth, class: "hidden" %>
            </div>
            <div class="form-group text-center">
                <%= form.submit 'Odeslat', :class => 'btn btn-outline-primary btn-md' %>
            </div>
        <% end %>
        <div class="text-center">
            <%= link_to 'Karta osoby', @person %> |
            <%= link_to 'Seznam osob', people_path %>
        </div>
    </div>
        
        
    
    

app/views/people/index.html.erb
<div class="row m-0 justify-content-center">
  <div class="col-xl-10 col-lg-12">
    <div class="text-center">
      <h1 class="display-3">Adresář</h1>
    </div>
    <div class="table-responsive">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>Jméno</th>
            <th>Příjmení</th>
            <th>Rodné číslo</th>
            <th>Telefonní číslo</th>
            <th>Pohlaví</th>
            <th>Datum narození</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @people.each do |person| %>
          <tr>
            <td class="align-middle"><%= person.name %></td>
            <td class="align-middle"><%= person.surname %></td>
            <td class="align-middle"><%= person.birthNumber %></td>
            <td class="align-middle"><%= person.phoneNumber %></td>
            <td class="align-middle"><%= person.sex %></td>
            <td class="align-middle"><%= person.dateOfBirth %></td>
            <td class="align-middle">
              <%= link_to 'Ukázat', person, :class => "btn btn-outline-primary"
              %>
            </td>
            <td class="align-middle">
              <%= link_to 'Editovat', edit_person_path(person), :class => "btn
              btn-outline-secondary" %>
            </td>
            <td class="align-middle">
              <%= link_to 'Smazat', person, :class => "btn btn-outline-danger",
              method: :delete, data: { confirm: 'Jste si jistý/á?' } %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center"><%= paginate @people %></div>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<% if @person.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>
 
    <ul>
    <% @person.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1 class="display-2 text-center">Přidat kontakt do adresáře</h1>    

<div class="container">
    <%= form_for @person do |form| %>
        <div class="form-group">
            <%= form.label :name, "Jméno:" %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :surname, "Příjmení:" %>
            <%= form.text_field :surname, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :birthNumber, "Rodné číslo:" %>
            <%= form.text_field :birthNumber, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= form.label :phoneNumber, "Telefon:" %>
            <%= form.text_field :phoneNumber, class: "form-control" %>
        </div>
        <div class="form-group text-center">
            <%= form.submit 'Odeslat', :class => 'btn btn-outline-primary btn-md' %>
            <a href="/people" class="btn btn-outline-secondary btn-md">Zpátky...</a>
        </div>
    <% end %>
</div>
    
    

app/views/people/show.html.erb
<div class="container">
  <div class="card mt-5">
    <div class="card-header">
      <%= @person.name %> <%= @person.surname %>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>Rodné číslo: </strong><%= @person.birthNumber %></li>
      <li class="list-group-item"><strong>Telefonní číslo: </strong><%= @person.phoneNumber %></li>
      <li class="list-group-item"><strong>Pohlaví: </strong><%= @person.sex %></li>
      <li class="list-group-item"><strong>Datum narození: </strong><%= @person.dateOfBirth %></li>
      <li class="list-group-item"><%= link_to 'Edit', edit_person_path(@person) %> |
      <%= link_to 'Back', people_path %></li>
    </ul> 
  </div>

  <h1 class="display-4 text-center mt-5">Seznam adres</h1>
  <%= link_to "Přidat adresu", 
            {:controller => "locations", 
            :action => "new", 
            :person_id => @person.id},
            :class => "btn btn-outline-primary" %>
  <div class="list-group mt-1">
   <% (@locations.where("person_id = ?",  @person.id)).each do |location| %>
    <a href="/locations/<%= location[:id] %>" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><i class="fas fa-city"></i> <strong>Město: </strong><%= location[:city] %></h5>
        <small>Vytvořeno: <%= location[:created_at] %></small>
      </div>
      <p class="mb-1"><i class="fas fa-road"></i> <strong>Ulice: </strong><%= location[:street] %></p>
      <small><i class="fas fa-mail-bulk"></i> <strong>PSČ: </strong><%= location[:psc] %></small>
    </a>
    <% end %>
  </div>
</div>